syntax = "proto3";

package order;

option go_package = "github.com/Fox216540/shop/proto/order-service/gen;proto";

service InternalOrderService {
    rpc PlaceOrder (PlaceOrderRequest) returns (Order);
    rpc CancelOrder (CancelOrderRequest) returns (CancelOrderResponse);
    rpc GetOrderById (GetOrderByIdRequest) returns (Order);
    rpc GetOrdersByUserId (GetOrdersByUserIdRequest) returns (GetOrdersByUserIdResponse);
}

message PlaceOrderRequest {
    string user_id = 1;
    repeated ItemRequest items = 2;
}

message ItemRequest {
    string product_id = 1;
    uint64 quantity = 2;
}

message Order {
    string id = 1;
    string order_num = 2;
    string user_id = 3;
    repeated Item items = 4;
    double total = 5;
    string status = 6;
}

message Item {
    Product product = 1;
    uint64 quantity = 2;
}

message Product {
    string id = 1;
    string name = 2;
    string img = 3;
    double price = 4;
}

message CancelOrderRequest {
    string user_id = 1;
    string order_id = 2;
}

message CancelOrderResponse {
    string order_id = 1;
}

message GetOrderByIdRequest {
    string order_id = 1;
}

message GetOrdersByUserIdRequest {
    string user_id = 1;
}

message OrderForList {
    string id = 1;
    string order_num = 2;
    string user_id = 3;
    double total = 4;
    string status = 5;
}

//TODO: подумать что возвращать
message GetOrdersByUserIdResponse {
    repeated OrderForList orders = 1;
}
