syntax = "proto3";

package order.interservice;

import "common/types.proto";
import "google/protobuf/empty.proto";

option go_package = "github.com/Fox216540/shop/proto/order-service/gen/interservice;proto";

service InterserviceService {
    //В metadata передавать userID ↓
    rpc CreteOrder (CreateOrderRequest) returns (common.Order);
    //В metadata передавать userID ↓
    rpc GetOrderById (common.OrderId) returns (common.Order);
    //В metadata передавать userID ↓
    rpc GetOrdersByUserId (google.protobuf.Empty) returns (GetOrdersByUserIdResponse);
    //В metadata передавать userID ↓
    rpc CancelOrder (common.OrderId) returns (common.OrderId);
}

message ItemRequest {
    string product_id = 1;
    uint64 quantity = 2;
}

message CreateOrderRequest {
    repeated ItemRequest items = 2;
}

message OrderForList {
    string id = 1;
    string order_num = 2;
    double total = 4;
    string status = 5;
}

message GetOrdersByUserIdResponse {
    repeated OrderForList orders = 1;
}
