syntax = "proto3";

package proto;

option go_package = "/;proto";

service AuthService {
    rpc SignUp (SignRequest) returns (SignResponse);
    rpc Login (LoginRequest) returns (TokensResponse);
    rpc DecodeToken (DecodeTokenRequest) returns (DecodeTokenResponse);
    rpc DeleteRefreshToken (DeleteRefreshTokenRequest) returns (DeleteSuccessResponse);
    rpc DeleteAllTokens (DeleteAllTokensRequest) returns (DeleteSuccessResponse);
    rpc NewPassword (NewPasswordRequest) returns (NewPasswordResponse);
    rpc RefreshTokens (NewTokensRequest) returns (TokensResponse);
}

message SignRequest {
    string user_id = 1;
    string password = 2;
}

message SignResponse {
    string hash = 1;
    string access_token = 2;
    string refresh_token = 3;
}

message LoginRequest {
    string user_id = 1;
    string password = 2;
    string hash = 3;
}

message TokensResponse {
    string access_token = 1;
    string refresh_token = 2;
}

enum TokenType {
    UNKNOWN = 0;      // Значение по умолчанию
    ACCESS = 1;       // Access-токен
    REFRESH = 2;      // Refresh-токен
}

message DecodeTokenRequest {
    string token = 1;
    TokenType token_type = 2;
}

message DecodeTokenResponse {
    string user_id = 1;
    string jti = 2;
}

message DeleteRefreshTokenRequest {
    string token = 1;
}

message DeleteSuccessResponse {
    string message = 1;
}

message DeleteAllTokensRequest {
    string token = 1;
}

message NewPasswordRequest {
    string old_password = 1;
    string hash = 2;
    string new_password = 3;
}

message NewPasswordResponse {
    string hash = 1;
}

message NewTokensRequest {
    string token = 1;
}





