syntax = "proto3";

package common;

option go_package = "github.com/Fox216540/shop/proto/common/gen;common";

//General:
message MessageResponse {
    string message = 1;
}

message Product {
    string id = 1;
    string name = 2;
    string img = 3;
    double price = 4;
}

//Auth-service:
message TokensResponse {
    string access_token = 1;
    string refresh_token = 2;
}

message DecodeTokenRequest {
    string token = 1;
}

message UserId {
    string id = 1;
}

//User-service:
message UserNameResponse {
    string name = 1;
}

message CredentialsRequest {
    string phone_or_email = 1;
    string password = 2;
}

message UserWithTokensResponse {
    common.UserNameResponse name = 1;
    common.TokensResponse tokens = 2;
    common.MessageResponse message = 3;
}