syntax = "proto3";

package basket.api;

import "common/types.proto";
import "google/protobuf/empty.proto";


option go_package = "github.com/Fox216540/shop/proto/basket-service/gen/api;basket";

service ApiService {
    //В metadata передавать userID ↓
    rpc GetBasket (google.protobuf.Empty) returns (GetBasketResponse);
    //В metadata передавать userID ↓
    rpc AddItemToBasket (AddItemToBasketRequest) returns (AddItemToBasketResponse);
    //В metadata передавать userID ↓
    rpc DeleteBasket (google.protobuf.Empty) returns (common.MessageResponse);
    //В metadata передавать userID ↓
    rpc RemoveItemFromBasket (RemoveItemFromBasketRequest) returns (common.MessageResponse);
}


message GetBasketResponse {
    repeated BasketItem items = 1;
    common.Money total = 2;
}

message AddItemToBasketRequest {
    string product_id = 1;
    uint64 quantity = 2;
}

message AddItemToBasketResponse {
    BasketItem item = 1;
}

message RemoveItemFromBasketRequest {
    string product_id = 1;
}

message BasketItem {
    common.Product product = 1;
    uint64 quantity = 2;
}
