syntax = "proto3";

package payment.interservice;

option go_package = "github.com/Fox216540/shop/proto/payment-service/gen/interservice;payment";

service InterserviceService {
    rpc CreatePayment (CreatePaymentRequest) returns (CreatePaymentResponse);
}

message CreatePaymentRequest {
    string order_id = 1;
    string value = 2;
    string currency = 3;
    string description = 4;
    string return_url = 5;
}

message CreatePaymentResponse {
    string payment_id = 1;
    string confirmation_url = 2;
    string status = 3;
}

